'use client';
import { useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, CalendarDays, Check, CheckCheck, ChevronLeft, ChevronRight, FileText, GraduationCap, LockKeyhole, PawPrint, ShieldCheck } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import budget from './budget.json';
const money = (pence: number) => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(pence / 100);
const movement = (pence: number) => `${pence > 0 ? '+' : pence < 0 ? '−' : ''}${money(Math.abs(pence))}`;

export default function Home() {
  const [index, setIndex] = useState(0);
  const month = budget.months[index];
  const chatgptPayment = budget.chatgpt.payments.find((payment) => payment.month === month.name);
  return <main id="top" className="budget-shell">
    <header className="topbar"><a className="wordmark" href="#top"><GraduationCap aria-hidden="true" size={25} />University budget</a><span className="privacy"><LockKeyhole aria-hidden="true" size={14} />Private</span></header>
    <section aria-labelledby="budget-title" className="intro"><div><p className="eyebrow">KING’S COLLEGE LONDON · 2026–27</p><h1 id="budget-title">Your university budget.</h1><p className="date-range">21 September 2026 – 20 September 2027</p></div><a className="document-button" href="/downloads/university-budget.pdf"><FileText size={18} aria-hidden="true" />Open budget PDF<ArrowUpRight size={17} aria-hidden="true" /></a></section>
    <section className="year-summary" aria-label="Budget totals"><div className="closing-card"><span className="summary-label">Projected final liquid balance</span><strong className="closing-value">{money(budget.totals.closing).split('.')[0]}<span>.{money(budget.totals.closing).split('.')[1]}</span></strong><div className="closing-note"><CheckCheck size={17} aria-hidden="true" />All 13 months reconcile</div></div><dl className="year-totals"><div><dt>Income during budget</dt><dd>{money(budget.totals.income)}</dd></div><div><dt>Planned spending</dt><dd>{money(budget.totals.spending)}</dd></div><div><dt>Protected savings</dt><dd>{money(budget.totals.savings)}</dd></div><div><dt>Liquid + savings</dt><dd>{money(budget.totals.combined)}</dd></div></dl></section>
    <div className="litter-note allowance-note"><CalendarDays size={20} aria-hidden="true" /><p><strong>Allowance £20 every other Friday</strong><span>18 September → 2 October → 16 October → 30 October. The budget starts at £0 on 21 September, so the 18 September payment is excluded. The first included payment is 2 October.</span></p></div>
    <div className="litter-note"><PawPrint size={20} aria-hidden="true" /><p><strong>Food £25 + litter £6.98</strong><span>Every two weeks, on the same dates. Litter is £3.49 per week.</span></p></div>
    <div className="workspace-grid">
      <section className="month-area" aria-labelledby="month-heading">
        <div className="section-heading"><h2 id="month-heading">Month by month</h2><span className="section-count">{index + 1} of 13</span></div>
        <div className="month-picker"><button className="icon-button" type="button" aria-label="Previous month" disabled={index === 0} onClick={() => setIndex(index - 1)}><ChevronLeft aria-hidden="true" /></button><Select value={String(index)} onValueChange={(value) => { if (value !== null) setIndex(Number(value)); }}><SelectTrigger className="month-select" aria-label="Choose a budget month"><SelectValue>{month.name}</SelectValue></SelectTrigger><SelectContent alignItemWithTrigger={false}>{budget.months.map((m, i) => <SelectItem className="month-option" value={String(i)} key={m.name}>{m.name}</SelectItem>)}</SelectContent></Select><button className="icon-button" type="button" aria-label="Next month" disabled={index === 12} onClick={() => setIndex(index + 1)}><ChevronRight aria-hidden="true" /></button></div>
        <div key={month.name} className="month-panel">
          <div className="month-title-line"><div><h3>{month.name}</h3><p>{month.period}</p></div><span className="pass-badge"><Check size={14} aria-hidden="true" />Checked</span></div>
          <dl className="month-metrics"><div><dt>Opening balance</dt><dd>{money(month.opening)}</dd></div><div><dt>Income</dt><dd>{money(month.income)}</dd></div><div><dt>Spending</dt><dd>{money(month.spending)}</dd></div><div><dt>To savings</dt><dd>{money(month.savings)}</dd></div></dl>
          <div className="month-close"><div><span>Closing balance</span><strong aria-live="polite">{money(month.closing)}</strong></div><span className={month.net >= 0 ? 'positive' : 'negative'}>{movement(month.net)}<small>net movement</small></span></div>
          <p className="month-context">{month.context}</p>
          {chatgptPayment && <p className="billing-month"><strong>ChatGPT {chatgptPayment.plan} · {money(chatgptPayment.amount)}</strong><span>{chatgptPayment.date} · included in subscriptions and bills</span></p>}
          <div className="spending-breakdown"><h4>Spending breakdown</h4><dl>{month.categories.filter((c) => c.amount > 0).map((c) => <div key={c.name}><dt><span>{c.name}</span><span className="spend-track" aria-hidden="true"><span style={{ width: `${c.amount / month.spending * 100}%` }} /></span></dt><dd>{money(c.amount)}</dd></div>)}</dl></div>
          <div className="payments-heading"><h4>Dated payments</h4><span>{month.rows.length} dates</span></div><p className="payment-help">Tap a date for every payment and its coverage notes.</p>
          <Accordion className="payment-list" multiple>{month.rows.map((row) => <AccordionItem key={row.date} value={row.date}><AccordionTrigger className="payment-trigger"><span className="payment-date">{row.date}<small>{row.details.map((d) => d.category.replace('Subscriptions / bills', 'Bills')).join(' · ')}</small></span><span className="payment-amount"><strong className={row.net >= 0 ? 'positive' : ''}>{movement(row.net)}</strong><small>{money(row.balance)} left</small></span></AccordionTrigger><AccordionContent className="payment-content"><dl className="payment-detail">{row.details.map((d) => <div key={d.category}><dt>{d.category}</dt><dd>{d.text}</dd></div>)}</dl></AccordionContent></AccordionItem>)}</Accordion>
        </div>
        <section className="category-panel" aria-labelledby="categories-heading"><h2 id="categories-heading">Category breakdowns</h2><p className="payment-help">Full budget period · 21 September 2026–20 September 2027</p><Accordion multiple>{budget.breakdowns.map((category) => <AccordionItem key={category.name} value={category.name}><AccordionTrigger className="category-trigger"><span>{category.name}</span><strong>{money(category.total)}</strong></AccordionTrigger><AccordionContent><dl className="category-items">{category.items.map((item) => <div key={item.name}><dt>{item.name}<small>{item.calculation}</small></dt><dd>{money(item.amount)}</dd></div>)}</dl>{category.note && <p className="category-note">{category.note}</p>}</AccordionContent></AccordionItem>)}</Accordion></section>
      </section>
      <aside className="support-column">
        <section className="download-panel billing-panel" aria-labelledby="billing-heading"><h2 id="billing-heading">ChatGPT billing plan</h2><dl className="billing-schedule"><div><dt>28 Sep, Oct, Nov &amp; Dec 2026</dt><dd>Plus · £20.00 per month</dd></div><div><dt>From 28 January 2027</dt><dd>Pro · £88.90 per month</dd></div><div><dt>Saving across four Plus payments</dt><dd>{money(budget.chatgpt.saving)}</dd></div><div><dt>ChatGPT total within this budget</dt><dd>{money(budget.chatgpt.total)}</dd></div></dl><p className="category-note">The £20 Plus amount is a planning assumption. All payments stay on the 28th.</p><div className="calendar-note"><CalendarDays size={20} aria-hidden="true" /><div><strong>Upgrade reminder</strong><p>28 January 2027 · 10 a.m. UK time</p><p>The September–December calendar payment events show Plus at £20. Their 8 a.m. times and notifications are preserved.</p><a className="text-link" href="https://www.google.com/calendar/event?eid=ODkzM243OG5xbHY3aHI1djk4ZWVxZ25rbWsgc3Zzc2VpZmlAbQ" target="_blank" rel="noopener noreferrer">Open upgrade reminder<ArrowUpRight size={16} aria-hidden="true" /></a></div></div><p className="category-note">The second student-loan instalment remains on 11 January 2027.</p></section>
        <section className="audit-panel" aria-labelledby="audit-heading"><div className="audit-icon"><ShieldCheck aria-hidden="true" size={24} /></div><p className="eyebrow">MATHS RECHECKED</p><h2 id="audit-heading">The maths checks out.</h2><p>{budget.totals.datedRows} dated rows. 13 monthly sections. No arithmetic errors found.</p><div className="audit-minimum"><span>Lowest balance after a scheduled date</span><strong>{money(budget.totals.minimumBalance)}</strong><span>{budget.totals.minimumDate} · excludes the £0 starting balance before the loan</span></div><p className="support-copy">The PDF, LaTeX, chart and source bundle all agree. Rechecked 11 September 2026 using the checker from the earlier independent audit.</p>
          <Accordion className="assumptions" multiple><AccordionItem value="allowance"><AccordionTrigger className="assumption-trigger">Allowance dates and starting balance</AccordionTrigger><AccordionContent className="assumption-content"><p>The £20 allowance repeats every 14 days from 18 September 2026. There are 26 receipts inside this budget, from 2 October 2026 to 17 September 2027, totalling £520. October and April each have three receipts.</p><p>The budget starts at £0 on 21 September. The 18 September payment is excluded entirely, so no money is carried into the budget.</p></AccordionContent></AccordionItem><AccordionItem value="dates"><AccordionTrigger className="assumption-trigger">Payment and travel dates</AccordionTrigger><AccordionContent className="assumption-content"><p>Some food and travel entries are weekly allocations. Actual daily balances depend on the payment dates. The three library visits in the week starting 7 June are covered by the May Travelcard only if they occur on 7–9 June.</p><p>This audit checks the document’s arithmetic at its stated prices and assumptions.</p></AccordionContent></AccordionItem></Accordion>
          <a className="text-link" href="/downloads/math-audit.md" download>Download full audit<ArrowDownToLine size={16} aria-hidden="true" /></a>
        </section>
        <section className="download-panel" aria-labelledby="documents-heading"><h2 id="documents-heading">Your documents</h2><a href="/downloads/university-budget.pdf" className="download-row"><span className="file-icon"><FileText aria-hidden="true" size={22} /></span><span><strong>Complete budget</strong><small>18-page PDF · category breakdown on pages 3–4</small></span><ArrowUpRight aria-hidden="true" size={19} /></a><a href="/downloads/university-budget-latex.zip" download className="download-row"><span className="file-icon"><ArrowDownToLine aria-hidden="true" size={22} /></span><span><strong>LaTeX source bundle</strong><small>Editable source + chart</small></span><ArrowDownToLine aria-hidden="true" size={19} /></a></section>
      </aside>
    </div>
    <footer><span>University Budget · 2026–27</span><span>Current plan · website updated 13 September 2026</span></footer>
  </main>;
}
